#!/bin/sh /etc/rc.common
START=95
USE_PROCD=1
start_service() {
 lua /usr/libexec/juliang-fastacl-domestic-dns.lua > /tmp/juliang-domestic-dns.json || return 1
 sing-box check -c /tmp/juliang-domestic-dns.json || return 1
 procd_open_instance
 procd_set_param command /usr/bin/sing-box run -c /tmp/juliang-domestic-dns.json
 procd_set_param respawn 3600 5 5
 procd_set_param stderr 1
 procd_close_instance
}
