include $(TOPDIR)/rules.mk

LUCI_TITLE:=JuLiangTK lightweight control center
LUCI_DEPENDS:=+luci-compat +luci-base +luci-mod-admin-full +iwinfo +rpcd-mod-iwinfo
LUCI_PKGARCH:=all

PKG_VERSION:=1.0.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

